name: Build

on:
  push:
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  PREFIX: /tmp/zmq
  LIBSODIUM_VERSION: 1.0.21
  LIBZMQ_VERSION: 4.3.5
  SCCACHE_CACHE_MULTIARCH: "1"
  SCCACHE_DIR: ".sccache"

jobs:
  build:
    container:
      image: ${{ matrix.image }}
    runs-on: ${{ matrix.runs-on || 'ubuntu-22.04' }}
    name: ${{ matrix.name }}

    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-universal
            runs-on: macos-14
          - name: manylinux_2_28_x86_64
            image: quay.io/pypa/manylinux_2_28_x86_64
          - name: manylinux_2_28_aarch64
            runs-on: ubuntu-24.04-arm
            image: quay.io/pypa/manylinux_2_28_aarch64

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          key: ${{ matrix.name }}
          path: ${{ env.SCCACHE_DIR }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: setup sccache
        run: |
          test -d $SCCACHE_DIR || mkdir -p $SCCACHE_DIR
          echo "SCCACHE_BASEDIRS=$PWD:$PREFIX"
          if [[ "$(uname)" == "Darwin" ]]; then
            echo "CXX=sccache clang++" >> ${GITHUB_ENV}
            echo "CC=sccache clang" >> ${GITHUB_ENV}
          else
            echo "CXX=sccache g++" >> ${GITHUB_ENV}
            echo "CC=sccache gcc" >> ${GITHUB_ENV}
          fi

      - name: build
        run: |
          bash install_libzmq.sh

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: "/tmp/zmq"
          if-no-files-found: error
  
  list-artifacts:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          skip-decompress: true
      - run: |
          ls -la dist/

  github-release:
    permissions:
      contents: write
    needs:
      - build
    environment: release
    runs-on: ubuntu-24.04
    if: github.ref_type == 'tag'
    # TODO: add builds to release
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          skip-decompress: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref.tag }}
          target_commitish: ${{ github.sha }}
          draft: true
          files: |
            dist/*
